'use strict';
const fs=require('node:fs'),path=require('node:path');
const {CARDS,SUITS}=require('../cards.js'),{noteOf}=require('../card-notes.js'),{SPREADS}=require('../spreads.js');
const {REVIEWED,SOURCE,SPREAD_CONTENT,GUIDES}=require('../content/editorial.cjs');
const EXAMPLES=require('../content/card-examples.cjs');
const ORIGIN='https://www.miloruna.com';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugOf=value=>String(value).toLocaleLowerCase('tr').replace(/ı/g,'i').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cardPath=card=>'/tarot-kartlari/'+slugOf(card.nameTr)+'/';
const json=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const p=value=>'<p>'+esc(value)+'</p>';
const link=(href,text)=>'<a href="'+esc(href)+'">'+esc(text)+'</a>';
const heading=(title,body)=>'<section class="article-section"><h2>'+esc(title)+'</h2>'+body+'</section>';
const readingLink=(id,label='Açılımı yap')=>'<a class="reading-link" data-reading-link="'+esc(id)+'" href="/?acilim='+esc(id)+'">'+esc(label)+' <span aria-hidden="true">↗</span></a>';
const sourceNote=()=>'<aside class="source-note">'+p('Görsel gelenek: Rider–Waite–Smith. Türkçe yorumlar ve okuma örnekleri Miloruna’nın sembolik yaklaşımını anlatır; örnekler yaşanmış kullanıcı hikâyeleri değildir.')+p('Tarihsel başvuru: '+SOURCE.name)+link(SOURCE.url,'Tarihsel kaynak metnini oku')+' · '+link('/hakkinda/','Miloruna’nın okuma yöntemini tanı')+'</aside>';
const CATEGORIES=[
  {id:'major',slug:'buyuk-arkana',name:'Büyük Arkana',intro:'22 Büyük Arkana kartı, başlangıç, seçim, değişim ve tamamlanma gibi geniş temaları ele alır. Her kartı görseli, düz ve ters anlamı, örnek konumu ve sana açtığı soruyla inceleyebilirsin.'},
  {id:'wands',slug:'asalar',name:'Asalar · Değnekler',intro:'Asalar, bazı destelerde Değnekler olarak adlandırılır. Ateş elementiyle ilişkilendirilen bu seri, heves, hareket, yaratıcılık ve bir işe başlama temasını ele alır. Sayı kartları ve saray kartları bu temanın farklı yönlerini düşündürür.'},
  {id:'cups',slug:'kupalar',name:'Kupalar',intro:'Kupalar serisi, duygular, yakınlık, ilişkiler ve hayal gücü etrafında okunur. Bir açılımda kartın konumu, bu duygunun bir destek mi yoksa zorlanan bir alan mı olarak ele alınacağını belirler.'},
  {id:'swords',slug:'kiliclar',name:'Kılıçlar',intro:'Kılıçlar serisi, düşünce, iletişim, açıklık ve çatışma temalarını ele alır. Yalnız zorlayıcı kartlardan oluşmaz; netlik, dinlenme ve farklı bir bakışa geçiş de bu serinin içindedir.'},
  {id:'pentacles',slug:'tilsimlar',name:'Tılsımlar · Paralar',intro:'Tılsımlar, bazı destelerde Paralar olarak adlandırılır. Emek, günlük kaynaklar, çalışma ve sürdürülebilirlik gibi somut yaşam temalarıyla okunur. Kartlar bir maddi kazancın garantisi değildir; kaynaklarla kurduğun ilişkiyi düşünmeye açar.'}
];
const categoryFor=card=>CATEGORIES.find(c=>c.id===(card.arcana==='major'?'major':card.suit));
const categoryPath=c=>'/tarot-kartlari/'+c.slug+'/';
const cardTiles=cards=>'<ul class="card-directory">'+cards.map(card=>'<li>'+link(cardPath(card),card.nameTr).replace('</a>','<img src="/'+esc(card.image)+'" alt="" width="350" height="600" loading="lazy" decoding="async"><span class="tile-keys">'+esc(card.keywords.slice(0,3).join(' · '))+'</span></a>')+'</li>').join('')+'</ul>';
const relatedCards=ids=>heading('İlgili kartları keşfet','<ul class="related-links">'+ids.map(id=>CARDS.find(c=>c.id===id)).filter(Boolean).map(card=>'<li>'+link(cardPath(card),card.nameTr+' tarot kartı')+'</li>').join('')+'</ul>');
const spreadTable=()=>'<div class="table-wrap" tabindex="0" role="region" aria-label="Tarot açılımlarının karşılaştırması"><table><thead><tr><th scope="col">Açılım</th><th scope="col">Kart</th><th scope="col">Kullanım</th></tr></thead><tbody>'+SPREADS.map(s=>'<tr><th scope="row">'+link('/'+SPREAD_CONTENT[s.id].slug+'/',SPREAD_CONTENT[s.id].title)+'</th><td>'+s.cardCount+'</td><td>'+esc(s.id==='daily'?'Günün odağı':s.id==='decision'?'İki yolun karşılaştırması':s.blurb)+'</td></tr>').join('')+'</tbody></table></div>';
function page(pathname,title,description,body,{kind='article',breadcrumbs=[]}={}){return {path:pathname,title:title+' | Miloruna',heading:title,description,body,kind,breadcrumbs};}
function pagesFor(){
  const pages=[];
  for(const card of CARDS){
    const note=noteOf(card.id),cat=categoryFor(card);
    if(!note||!EXAMPLES[card.id])throw new Error('Card lacks editorial content: '+card.id);
    const image='<figure class="article-art"><img src="/'+esc(card.image)+'" alt="'+esc(card.nameTr+' kartının Rider–Waite–Smith görseli')+'" width="350" height="600" fetchpriority="high" decoding="async"><figcaption>'+esc(card.nameTr)+' · '+esc(card.name)+'</figcaption></figure>';
    const intro='<div class="card-opening">'+image+'<div><p class="eyebrow">'+esc(cat.name)+'</p>'+p(card.upright)+'<ul class="keywords">'+card.keywords.map(k=>'<li>'+esc(k)+'</li>').join('')+'</ul>'+p('Bu kartın açılımdaki konumu, aşağıdaki temaları hangi soruyla okuyacağını belirler.')+readingLink('three','Bu kartı bir açılımda düşün')+'</div></div>';
    const body=intro+heading('Kartın görselinde ne var?',p(note.scene))+heading('Düz anlam',p(card.upright)+p(note.ask))+heading('Ters anlam',p(card.reversed)+p(note.askReversed))+(card.loveWork?heading('Aşk ve iş bağlamında',p(card.loveWork)):'')+heading('Açılımda bir örnek',p(EXAMPLES[card.id]))+relatedCards(CARDS.filter(c=>c.id!==card.id&&(c.arcana==='major'?card.arcana==='major':c.suit===card.suit)).slice(Math.max(0,CARDS.filter(c=>c.arcana===card.arcana&&(c.arcana==='major'||c.suit===card.suit)).indexOf(card)-1),Math.max(0,CARDS.filter(c=>c.arcana===card.arcana&&(c.arcana==='major'||c.suit===card.suit)).indexOf(card)-1)+3).map(c=>c.id))+heading('Yorumun çerçevesi',p('Bu anlamları tek bir kesin sonuca dönüştürmek yerine sorunun bağlamıyla birlikte oku. '+card.nameTr+' kartının düşündürdüğü tema, aynı açılımda yanına gelen kartlarla farklı bir vurgu kazanabilir.')+link('/rehber/tarot-nasil-bakilir/','Kartları konumlarıyla birlikte okumayı öğren'))+sourceNote();
    pages.push(page(cardPath(card),card.nameTr+' tarot kartı: düz ve ters anlamı',card.nameTr+' tarot kartının düz ve ters anlamını, görsel sembollerini ve açılımdaki örnek yorumunu öğren. '+card.keywords.slice(0,3).join(', ')+'.',body,{breadcrumbs:[{name:'Tarot kartları',path:'/tarot-kartlari/'},{name:cat.name,path:categoryPath(cat)}]}));
  }
  for(const cat of CATEGORIES){
    const cards=CARDS.filter(card=>(card.arcana==='major'?'major':card.suit)===cat.id);
    pages.push(page(categoryPath(cat),cat.name+' tarot kartları ve anlamları',cat.name+' serisindeki '+cards.length+' tarot kartını görselleri, düz ve ters anlamlarıyla keşfet.',p(cat.intro)+cardTiles(cards)+heading('Kartı nasıl okuyabilirim?',p('Önce kartın kendi temasına, sonra bulunduğu konumun sorusuna bak. Aynı kart destek, engel veya gidişat konumunda farklı bir yönü düşündürebilir.')+link('/rehber/tarot-nasil-bakilir/','Tarot okuma adımlarını incele')),{kind:'collection',breadcrumbs:[{name:'Tarot kartları',path:'/tarot-kartlari/'}]}));
  }
  pages.push(page('/tarot-kartlari/','78 tarot kartı ve anlamları','78 tarot kartını keşfet: 22 Büyük Arkana ve dört seride 56 Küçük Arkana. Her kartın görseli, düz ve ters anlamı ve örnek okuması.',p('Miloruna’nın Rider–Waite–Smith düzenindeki 78 kartını aşağıda bulabilirsin. Bir kartı seçerek görseldeki sembolleri, düz ve ters anlamı, kendine sorabileceğin soruyu ve açılım örneğini oku.')+'<nav class="collection-nav" aria-label="Kart serileri">'+CATEGORIES.map(c=>link('#'+c.slug,c.name)).join('')+'</nav>'+CATEGORIES.map(c=>'<section class="article-section" id="'+c.slug+'"><h2>'+link(categoryPath(c),c.name)+'</h2>'+p(c.intro)+cardTiles(CARDS.filter(card=>(card.arcana==='major'?'major':card.suit)===c.id))+'</section>').join(''),{kind:'collection'}));
  for(const spread of SPREADS){
    const copy=SPREAD_CONTENT[spread.id];
    const positions='<ol class="position-list">'+spread.positions.map(pos=>'<li><h3>'+pos.index+'. '+esc(pos.label)+'</h3>'+p(pos.prompt)+'</li>').join('')+'</ol>';
    const body='<p class="answer-lead">'+esc(copy.summary)+'</p><p class="reading-facts">'+spread.cardCount+' kart · Yaklaşık '+spread.estMinutes+' dakika · Ücretsiz</p>'+readingLink(spread.id)+heading('Ne zaman bu açılımı seçebilirsin?',p(copy.use))+heading('Kartların konumları',positions)+heading('Sorunu nasıl ifade edebilirsin?',p(copy.question)+link('/rehber/tarot-sorulari/','Daha fazla tarot sorusu örneği oku'))+heading('Örnek bir okuma',p(copy.example))+heading('Yorumu kendi deneyimine bağla',p(copy.practice))+heading('Miloruna’da nasıl çalışır?',p(copy.product))+heading('Merak edilenler',copy.questions.map(([q,a])=>'<h3>'+esc(q)+'</h3>'+p(a)).join(''))+relatedCards(copy.related)+sourceNote()+readingLink(spread.id,'Bu açılımı dene');
    pages.push(page('/'+copy.slug+'/',copy.title,copy.description,body));
  }
  for(const guide of GUIDES){
    let body='<p class="answer-lead">'+esc(guide.summary)+'</p>';
    if(guide.comparison)body+=spreadTable();
    body+=guide.sections.map(s=>heading(s.heading,s.paragraphs.map(p).join('')+(s.items?'<ul class="prose-list">'+s.items.map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul>':''))).join('');
    body+=heading('Bir sonraki adım','<ul class="related-links">'+guide.related.map(slug=>GUIDES.find(g=>g.slug===slug)).map(g=>'<li>'+link('/rehber/'+g.slug+'/',g.title)+'</li>').join('')+'</ul>'+readingLink('three','Üç kart açılımını dene'))+sourceNote();
    pages.push(page('/rehber/'+guide.slug+'/',guide.title,guide.description,body,{breadcrumbs:[{name:'Tarot rehberi',path:'/rehber/'}]}));
  }
  pages.push(page('/rehber/','Tarot rehberi: kartlar, sorular ve açılımlar','Tarota yeni başlayanlar için Miloruna rehberi: tarot nedir, nasıl bakılır, soru nasıl hazırlanır ve hangi açılım seçilir?',p('Kartları tanımak kadar sorunun çerçevesini ve açılımdaki konumları anlamak da okumayı şekillendirir. Aşağıdaki rehberlerden birini seç; sonra öğrendiğini bir açılımda deneyebilirsin.')+'<ul class="guide-directory">'+GUIDES.map(g=>'<li><h2>'+link('/rehber/'+g.slug+'/',g.title)+'</h2>'+p(g.summary)+'</li>').join('')+'</ul>'+heading('Açılımını seç',spreadTable()),{kind:'collection'}));
  pages.push(page('/hakkinda/','Miloruna hakkında ve okuma yöntemi','Miloruna nasıl çalışır? Ücretsiz tarot açılımları, Rider–Waite–Smith destesi, yorum yöntemi ve kart rehberinin kaynak yaklaşımı.',
    '<p class="answer-lead">Miloruna, Türkçe tarot kartlarını kendin seçerek niyetini ve içinde bulunduğun durumu düşünmen için hazırlanmış ücretsiz bir okuma deneyimidir.</p>'+heading('Miloruna’da neler var?',p('78 kartlık Rider–Waite–Smith düzeni ve altı açılım bulunur: günlük kart, üç kart, ilişki, kariyer, iki yolun karşılaştırıldığı karar açılımı ve on kartlık Kelt Haçı. Üyelik oluşturmadan açılım yapabilir, kart rehberini okuyabilirsin.'))+heading('Yorumlar nasıl hazırlanır?',p('Temel yorum, kartların düz veya ters anlamını, açılımdaki konumunu ve seçilen konuyu birlikte ele alan yerel bir yorum motoruyla hazırlanır. Her kartın görsel sahnesi ve düşünme soruları da okumaya eşlik eder. Kartlar bir başkasının düşüncesine erişen veya kesin bir sonucu doğrulayan bir araç olarak sunulmaz.')+p('Ek yorum hizmeti yapılandırılmışsa uygulama sunucusu seçilen kartları ve okuma bağlamını bir model sağlayıcısına iletebilir. Bu hizmetin yanıtı alınamazsa yerel kart yorumu kullanılmaya devam eder.'))+heading('Rehberin yayıncısı ve kaynakları',p('Bu rehberin yayıncısı Miloruna’dır. Kart açıklamaları ve örnek okumalar, uygulamanın kullandığı kart verileri ile sembolik okuma yaklaşımına göre hazırlanmıştır. Örnekler öğretici senaryolardır; gerçek kullanıcı hikâyesi veya sonuç kanıtı değildir.')+p('A. E. Waite’ın The Pictorial Key to the Tarot eseri ve Pamela Colman Smith’in görsel dili tarihsel başvuru noktalarıdır. Bu rehberdeki çağdaş Türkçe açıklamalar birebir tarihsel alıntı veya dışarıdan verilmiş bir uzman onayı olarak sunulmaz.')+link(SOURCE.url,SOURCE.name))+heading('Okumalar nerede saklanır?',p('Okuma geçmişi kullandığın tarayıcının yerel depolamasında tutulur. Başka bir cihazda otomatik görünmez; tarayıcı verileri temizlenirse kayıtlar silinebilir. Uygulamadaki geçmiş ekranından mevcut kayıtlarını görebilirsin.')+link('/gizlilik/','Veri kullanımını incele'))+heading('Bir yerden başla',link('/tarot-kartlari/','78 tarot kartını keşfet')+' · '+link('/rehber/','Tarot rehberini oku')+'<p>'+readingLink('daily','Günün kartını çek')+'</p>')));
  pages.push(page('/gizlilik/','Miloruna gizlilik ve veri kullanımı','Miloruna’da yerel okuma geçmişi, tercih kayıtları, Analytics ve isteğe bağlı sunucu yorumunun veri akışını öğren.',
    '<p class="answer-lead">Miloruna’da okuma geçmişi ve tercihler bu cihazdaki tarayıcıda saklanır. Site ziyaretlerinin anlaşılması için Google Analytics kullanılır; ek yorum hizmeti açıksa okuma bağlamı sunucu üzerinden sağlayıcıya iletilebilir.</p>'+heading('Cihazında saklanan kayıtlar',p('Seçtiğin kartlar, yazdığın okuma bilgileri, yorumlar ve tercihler tarayıcının yerel depolamasında tutulur. Bu kayıtlar cihazlar arasında otomatik eşitlenmez. Tarayıcı depolaması kullanılamadığında uygulama geçici oturumla çalışabilir ve kayıtların kalıcı olmadığını belirtir.')+p('Okumalarım ekranındaki kayıtları uygulama üzerinden silebilirsin. Bütün site verilerini kaldırmak için tarayıcının Miloruna’ya ait site verilerini temizleyebilirsin; bu işlem kayıtlı okumalarını ve tercihlerini kaldırır.'))+heading('Google Analytics',p('Miloruna ziyaret ve kullanım ölçümü için Google Analytics 4 kullanır. Sayfa adresi, ziyaret kaynağı, tarayıcı/cihaz bilgisi ve Analytics’in kendi ziyaret tanımlayıcıları bu hizmet tarafından işlenebilir.')+p('Miloruna’nın özel açılım etkinlikleri yalnız açılımın türünü gönderir. Yazdığın soru, kişi adı, iki seçeneğin metni, yorum metni veya okuma kimliği bu özel etkinliklere eklenmez.')+link('https://policies.google.com/privacy','Google’ın veri kullanımını incele'))+heading('Sunucu üzerinden ek yorum',p('Ek yorum bağlantısı etkinse soru, varsa kişi adı ve iki seçenek, seçilen kartlar ve konumları uygulama sunucusuna gönderilir. Sunucu, yorum hazırlanması için gerekli bağlamı yapılandırılan sağlayıcıya aktarabilir. Geçmiş arşivinin tamamı, cihaz kimliği ve gizli deste sırası bu yorum isteğine eklenmez.')+p('Sunucu isteğini hizmetin çalışması ve kötüye kullanımın sınırlanması için hosting altyapısı işler. Bu sayfa sağlayıcı veya hosting kayıtlarının hiç tutulmadığını vaat etmez. Bağlantı yoksa temel yerel yorumla okuma tamamlanabilir.'))+heading('Paylaşım ve dışa aktarma',p('Paylaşım, yedek veya takvim dosyası indirdiğinde dosyanın nerede saklanacağını ve kimlerle paylaşılacağını sen seçersin. Soru veya yorum içeren bir dosyayı paylaşmadan önce içeriğini gözden geçirebilirsin.'))+heading('Rehber ve açılım adresleri',p('Kart ve rehber sayfaları herkese açıktır. Rehberden açılıma geçiş bağlantıları yalnız açılım türünü içerir; soru, kişi adı veya yorum bu adreslere eklenmez. Kullanıcıya ait okuma geçmişi site haritasında listelenmez.'))));
  const paths=pages.map(p=>p.path);
  if(pages.length!==98||new Set(paths).size!==98)throw new Error('Discovery page count or path collision');
  return pages;
}
function structured(page){
  const url=ORIGIN+page.path;
  const graph=[{'@type':'Organization','@id':ORIGIN+'/#publisher',name:'Miloruna',url:ORIGIN+'/'},{'@type':'WebSite','@id':ORIGIN+'/#website',name:'Miloruna',url:ORIGIN+'/',inLanguage:'tr-TR',publisher:{'@id':ORIGIN+'/#publisher'}},{'@type':page.kind==='article'?'Article':'CollectionPage','@id':url+'#content',url,headline:page.heading,name:page.heading,description:page.description,inLanguage:'tr-TR',isPartOf:{'@id':ORIGIN+'/#website'},publisher:{'@id':ORIGIN+'/#publisher'},...(page.kind==='article'?{author:{'@id':ORIGIN+'/#publisher'},datePublished:REVIEWED,dateModified:REVIEWED,mainEntityOfPage:url}:{} )}];
  graph.push({'@type':'BreadcrumbList',itemListElement:[{name:'Miloruna',path:'/'},...page.breadcrumbs,{name:page.heading,path:page.path}].map((b,i)=>({'@type':'ListItem',position:i+1,name:b.name,item:ORIGIN+b.path}))});
  return {'@context':'https://schema.org','@graph':graph};
}
function renderPage(page){
  const analytics=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').match(/<!-- Google tag \(gtag.js\) -->[\s\S]*?<\/script>\s*<script>[\s\S]*?<\/script>/)?.[0]||'';
  const breadcrumbs=[{name:'Miloruna',path:'/'},...page.breadcrumbs];
  return '<!doctype html>\n<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#070d19">'+analytics+'\n<title>'+esc(page.title)+'</title><meta name="description" content="'+esc(page.description)+'"><link rel="canonical" href="'+ORIGIN+page.path+'"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">'+
    '<meta property="og:site_name" content="Miloruna"><meta property="og:locale" content="tr_TR"><meta property="og:type" content="'+(page.kind==='article'?'article':'website')+'"><meta property="og:title" content="'+esc(page.title)+'"><meta property="og:description" content="'+esc(page.description)+'"><meta property="og:url" content="'+ORIGIN+page.path+'"><meta property="og:image" content="'+ORIGIN+'/assets/night/hero-card-strip.webp"><meta property="og:image:alt" content="Miloruna tarot kartları"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'+esc(page.title)+'"><meta name="twitter:description" content="'+esc(page.description)+'"><meta name="twitter:image" content="'+ORIGIN+'/assets/night/hero-card-strip.webp">'+
    '<link rel="icon" type="image/png" sizes="96x96" href="/favicon.png"><link rel="stylesheet" href="/night.tokens.css?v=4"><link rel="stylesheet" href="/guide.css?v=1"><script src="/discovery.js?v=1" defer></script><script type="application/ld+json">'+json(structured(page))+'</script></head>\n<body><a class="skip-link" href="#content">İçeriğe geç</a><header class="guide-header"><a class="guide-brand" href="/" aria-label="Miloruna ana sayfa"><img src="/assets/brand/miloruna-mark.svg" alt="" width="36" height="36">Miloruna</a><nav aria-label="Ana menü">'+link('/','Açılım yap')+link('/tarot-kartlari/','Kartlar')+link('/rehber/','Rehber')+'</nav></header><main id="content" class="article-main"><nav class="breadcrumbs" aria-label="Sayfa yolu">'+breadcrumbs.map(b=>link(b.path,b.name)).join('<span aria-hidden="true">/</span>')+'</nav><article><header class="article-heading"><p class="eyebrow">Miloruna · '+(page.kind==='article'?'Okuma rehberi':'Keşfet')+'</p><h1>'+esc(page.heading)+'</h1><p class="byline">Miloruna · <time datetime="'+REVIEWED+'">7 Ekim 2026</time></p></header>'+page.body+'</article></main><footer class="guide-footer"><p>Biraz da kendini dinle.</p><nav aria-label="Alt menü">'+link('/hakkinda/','Miloruna hakkında')+link('/gizlilik/','Gizlilik')+link('/rehber/','Tarot rehberi')+'</nav></footer></body></html>\n';
}
function writeDiscovery(outDir){
  const pages=pagesFor();
  for(const page of pages){const dir=path.join(outDir,page.path);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),renderPage(page));}
  const paths=['/',...pages.map(p=>p.path)];
  fs.writeFileSync(path.join(outDir,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+paths.map(p=>'  <url><loc>'+ORIGIN+p+'</loc><lastmod>'+REVIEWED+'</lastmod></url>').join('\n')+'\n</urlset>\n');
  fs.writeFileSync(path.join(outDir,'robots.txt'),'User-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: '+ORIGIN+'/sitemap.xml\n');
  return paths;
}
module.exports={pagesFor,renderPage,writeDiscovery,slugOf};
